- name: Delete {{APP_LOCATION}} Directory
  ansible.builtin.file:
    path: "{{APP_LOCATION}}"
    state: absent

- name: Create {{APP_LOCATION}} Directory
  ansible.builtin.file:
    path: "{{APP_LOCATION}}"
    state: directory

- name: Download {{COMPONENT}} code
  ansible.builtin.get_url:
    url: http://{{NEXUS_URL}}/repository/{{COMPONENT}}/com/expense/{{COMPONENT}}/{{APPVERSION}}/{{COMPONENT}}-{{APPVERSION}}.zip
    dest: /tmp/{{COMPONENT}}.zip

- name: unzip {{COMPONENT}} code
  ansible.builtin.unarchive:
    src: /tmp/{{COMPONENT}}.zip # by default checks in ansible server
    dest: "{{APP_LOCATION}}"
    remote_src: yes